### ISSUE TITLE
Attempted payments when no WRLD is available in wallet fail silently

### ISSUE THREAD

**Issue by alfiejfs** [NFT-Worlds/WRLD-Payments-API#29]

**Comment by alfiejfs** [comment]
I am not entirely convinced, although there is an error message sometimes, that it happens everytime - can someone look into this?

**Comment by Jaxkr** [comment]
This is because the transaction itself is valid (it's a correct call to the smart contract and you have polygon to pay for it), but it fails much later after being mined and executed. Unlike standard transactions of a native gas token (Eth or Matic) which are not valid with insufficient balance, ERC20 transactions are checked for sufficient balance when _mined, not when they enter the mempool_.

Here's an example of such a failed transaction: https://polygonscan.com/tx/0x3debc20695bca48dba926784562300cf16f2cbfbb3f45ed8a97d9d95a8276ec3

We've created a feature that mitigates this which we'll be releasing publicly very soon.

**Comment by alfiejfs** [comment]
I see. Is it be possible too, when the transaction fails, to see the amount that has failed so the transaction can be repeated later also? As far as I can tell that isn't stored on-chain anywhere. I appreciate that this is out of scope of the payments API specifically, but perhaps you know. 

Appreciate the quick and helpful resposne!
